### ISSUE TITLE
"Failed to transcribe audio"

### ISSUE THREAD

**Issue by lcamus** [oneai-nlp/oneai-node#10]
Hi,
I just tried to run the asynchronous pipeline sample snipet (https://docs.oneai.com/docs/asynchronous-pipelines).
And I get the 40012 error code :

{"result":{"status_code":40012,"message":"Failed to transcribe audio","details":null,"request_id":"6855d38a-588e-414c-8ba0-02649471c997"},"task_id":"6855d38a-588e-414c-8ba0-02649471c997","status":"FAILED","completion_time":"2023-01-08T19:48:22.043000","creation_time":"2023-01-08T19:48:19.043000"}

I tried with 3 different files/formats and each time the same result.

Thanks for your help.

**Comment by michgur** [comment]
Can you send the code you're using?
I only see a curl example in the link you sent

Thanks,
// michael

**Comment by lcamus** [comment]
dear Michael,

There is only a curl command (see below).
Thanks for your support

curl -X POST \
> 'https://api.oneai.com/api/v0/pipeline/async' \
> -H 'accept: application/json' \
> -H 'Content-Type: application/json' \
> -H 'api-key: <my_api_key>' \
> -d '{
>     "input": "
> https://storage.googleapis.com/web-assests-oneai/How%20I%20create%20long%20hours%20of%20Deep%20Work%20-%20PhD%20student.wav
> ",
>     "input_type": "conversation",
>         "content_type": "audio/wav",
>     "steps": [
>       {
>         "skill": "transcribe",
>         "params": {
>           "speaker_detection": true
>         }
>       },
>       {
>         "skill": "summarize"
>       }
>     ]
> }'
>

**Comment by michgur** [comment]
I'll email you (as this is not related to the node sdk)

thanks,
// michael

**Comment by michgur** [comment]
closed as is unrelated to the node SDK

**Comment by michgur** [comment]
closed as is unrelated to the node SDK
