### ISSUE TITLE
Not getting the latest change on the npm SDK package. I cannot see "transcribe" method in the index.ts

### ISSUE THREAD

**Issue by romain130492** [oneai-nlp/oneai-node#5]
## Description

Hey,
When using `transcribe` with the Node packages I'm getting the error `transcribe` is not a function
```js
 const pipeline = new oneai.Pipeline(oneai.skills.transcribe());
```

I checked the package in the node_module, and I simply don't have that method in index.ts. However, I can see that you added that method 8 days ago on github. 

Kindly

**Comment by michgur** [comment]
v0.1.9 was published, with 'transcribe' included
