### ISSUE TITLE
htmlArticle output is missing from OutputFields object

### ISSUE THREAD

**Issue by reishapira** [oneai-nlp/oneai-node#8]
Hi there, we've been using the htmlArticle skill but currently using untyped access to it in the output object since it doesn't appear to be part of the type signature. 

Just wanted to point it out in case you were planning on adding more to the output signatures in the future.

Enjoying the service so far, thanks!

**Comment by michgur** [comment]
thanks for reaching out!

I published now a new version (0.4.7) which includes htmlArticle as a typed field
